# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mia Nakkula
tagline:             'A simple story writer'
description:         'My ramblings are found here.'
url:                 https://nakkula.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Mia Nakkula
  url:               
  email:             

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/ariestiyansyah
twitter:			http://twitter.com/ariestiyansyah
disqus:             testnaringu

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu